In [1]:
import torch

In [2]:
from src.model import *

ModuleNotFoundError: No module named 'rma'

In [ ]:
config = {
    "num_blocks":2,
    "embed_dim":256,
    "num_heads":4,
    "gru_bias":0.0
}

In [ ]:
s = 0
for i in GatedTransformerXL(config,input_dim=1,max_episode_steps=100).state_dict().keys():
    print(i)
    s+=1
print(s)

In [ ]:
from torch.utils.tensorboard import SummaryWriter
import numpy as np
import os
import time

run_id = "ok"

In [ ]:
from src.writer import Writer

In [ ]:
if not os.path.exists("./test"):
    os.makedirs("./test")
writer = Writer("./test/ok/")

In [ ]:
for i in range(100):
    writer.add(i,np.random.rand(),np.random.rand(),np.random.rand(),np.random.rand(),np.random.rand(),np.random.rand())

In [ ]:
torch.tril(torch.ones((5, 5)), diagonal=-1)

tensor([[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.]])

In [4]:
torch.tensor([0,0,1]).logical_not()

tensor([ True,  True, False])

In [7]:
a = torch.tensor([1,0,0,1])
a[torch.where(a==1)[0]]

tensor([1, 1])

In [1]:
a = {"a":1,"b":2}

In [3]:
a.items()

dict_items([('a', 1), ('b', 2)])